In [19]:
import torch;
import pandas as pd;
#supress pandas warnings
pd.options.mode.chained_assignment = None  # default='warn'

In [20]:
# read the dataset from the file updated_locational_prices.csv
data = pd.read_csv('updated_locational_prices.csv');
data

,date,time,start_location,end_location,total_price,start_lat,start_lon,end_lat,end_lon,duration
0,09/28/2024,19:30:41,"220 Bloor St W, Toronto, ON M5S 1T8","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",38.11,43.668900,-79.396002,43.643629,-79.379153,941s
1,09/28/2024,19:30:41,"127 Avenue Rd, Toronto, ON M5R 2H4","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",40.52,43.673400,-79.396002,43.643629,-79.379153,969s
2,09/28/2024,19:30:41,"2 Bloor St E, Toronto, ON M4W 1A8, Canada","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",36.61,43.671139,-79.386717,43.643629,-79.379153,933s
3,09/28/2024,19:30:41,"32 Davenport Rd, Toronto, ON M5R 0B5","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",14.09,43.673400,-79.389802,43.643629,-79.379153,948s
4,09/28/2024,19:30:41,"75 Queen's Park Cres E, Toronto, ON M5S 1K7, C...","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",18.03,43.666639,-79.392917,43.643629,-79.379153,849s
...,...,...,...,...,...,...,...,...,...,...
103,09/28/2024,20:55:37,"75 Queen's Park Cres E, Toronto, ON M5S 1K7, C...","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",35.55,43.666639,-79.392917,43.643629,-79.379153,848s
104,09/28/2024,20:57:02,"2 Bloor St E, Toronto, ON M4W 1A8, Canada","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",36.61,43.671139,-79.386717,43.643629,-79.379153,954s
105,09/28/2024,20:57:02,"Yorkville, Toronto, Ontario, Canada","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",34.24,43.671139,-79.392917,43.643629,-79.379153,1020s
106,09/28/2024,20:57:02,"32 Davenport Rd, Toronto, ON M5R 0B5","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",39.53,43.673400,-79.389802,43.643629,-79.379153,958s
107,09/28/2024,20:57:02,"220 Bloor St W, Toronto, ON M5S 1T8","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",38.11,43.668900,-79.396002,43.643629,-79.379153,1005s

In [24]:
# get the time, start_location, end_location, price, and duration columns
needed = data[['time', 'start_location', 'end_location', 'total_price', 'duration']];
needed

# strip the s from the duration column and put it in the column name 
needed['duration'] = needed['duration'].str.strip('s');
needed.rename(columns = {'duration': 'duration_seconds'}, inplace = True);
# convert the duration column to a float
needed['duration_seconds'] = needed['duration_seconds'].astype(float);
needed

,time,start_location,end_location,total_price,duration_seconds
0,19:30:41,"220 Bloor St W, Toronto, ON M5S 1T8","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",38.11,941.0
1,19:30:41,"127 Avenue Rd, Toronto, ON M5R 2H4","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",40.52,969.0
2,19:30:41,"2 Bloor St E, Toronto, ON M4W 1A8, Canada","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",36.61,933.0
3,19:30:41,"32 Davenport Rd, Toronto, ON M5R 0B5","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",14.09,948.0
4,19:30:41,"75 Queen's Park Cres E, Toronto, ON M5S 1K7, C...","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",18.03,849.0
...,...,...,...,...,...
103,20:55:37,"75 Queen's Park Cres E, Toronto, ON M5S 1K7, C...","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",35.55,848.0
104,20:57:02,"2 Bloor St E, Toronto, ON M4W 1A8, Canada","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",36.61,954.0
105,20:57:02,"Yorkville, Toronto, Ontario, Canada","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",34.24,1020.0
106,20:57:02,"32 Davenport Rd, Toronto, ON M5R 0B5","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",39.53,958.0
107,20:57:02,"220 Bloor St W, Toronto, ON M5S 1T8","Scotiabank Arena, 40 Bay St, Toronto, Ontario ...",38.11,1005.0

In [25]:
# Get the average duration and total_price for each start location
# group the data by the start location
grouped = needed.groupby('start_location');
# get the average duration and total_price for each start location
average_duration = grouped['duration_seconds'].mean();
average_price = grouped['total_price'].mean();
# create a new dataframe to store the average duration and total_price
average_df = pd.DataFrame({'average_duration': average_duration, 'average_price': average_price});
average_df

,average_duration,average_price
start_location,,
"127 Avenue Rd, Toronto, ON M5R 2H4",997.750000,31.843333
"2 Bloor St E, Toronto, ON M4W 1A8, Canada",938.916667,31.641667
"220 Bloor St W, Toronto, ON M5S 1T8",988.583333,34.835000
"30 Hillsboro Ave, Toronto, ON M5R 1S7, Canada",1018.000000,30.430000
"32 Davenport Rd, Toronto, ON M5R 0B5",950.166667,30.614167
"75 Queen's Park Cres E, Toronto, ON M5S 1K7, Canada",850.333333,30.759167
"77 Bloor St W, Toronto, ON M5S 1M2",890.750000,31.541667
"86 Bedford Rd, Toronto, ON M5R 2K9, Canada",1067.000000,34.003333
"Yorkville, Toronto, Ontario, Canada",1043.750000,29.265000